namespace GropMng.Web.Areas.Admin.Models.Common;

/// <summary>
/// Represents the shared configuration required to render an admin DataTable shell.
/// </summary>
public class AdminDataTableModel
{
    /// <summary>
    /// Gets or sets the HTML table id.
    /// </summary>
    public string TableId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the CSS classes applied to the table element.
    /// </summary>
    public string TableCssClass { get; set; } = "table table-hover";

    /// <summary>
    /// Gets or sets the CSS classes applied to the wrapping div.
    /// </summary>
    public string WrapperCssClass { get; set; } = "card-datatable table-responsive";

    /// <summary>
    /// Gets or sets the configured column headers.
    /// </summary>
    public IList<AdminDataTableColumnModel> Columns { get; set; } = new List<AdminDataTableColumnModel>();
}

/// <summary>
/// Represents a single DataTable header column.
/// </summary>
public class AdminDataTableColumnModel
{
    /// <summary>
    /// Gets or sets the header content.
    /// Supports safe HTML generated by the application when required.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets optional CSS classes for the header cell.
    /// </summary>
    public string? CssClass { get; set; }

    /// <summary>
    /// Gets or sets optional inline style for the header cell.
    /// </summary>
    public string? Style { get; set; }
}